import './CLI.tests.ts';
import './commands/.tests.ts';
import './help/.tests.ts';
import './matcher/CLICommandMatcher.tests.ts';
import './parser/CLICommandInvocationParser.tests.ts';
import './scaffolding/.tests.ts';
import './styling/.tests.ts';
import './types/.tests.ts';
import './utils/.tests.ts';
